version: "3"

networks:
  mlops-net:
    driver: bridge

services:
  python-service:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile 
    command: tail -f /dev/null
    container_name: "python-container"
    networks:
      - mlops-net
    ports:
      - "8237:8237"
      - "8080:8080"
    volumes:
      - .:/app
